FROM base

RUN apt-get update

RUN apt-get install -y openjdk-7-jre-headless curl bsdtar

#RUN echo "JAVA_HOME=/usr/lib/jvm/java-7-oracle" >> /etc/environment

ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/jre
