FROM fuse

WORKDIR /home/fuse/fuse-fabric

#ENTRYPOINT ["/home/fuse/fuse-fabric/bin/fusefabric"]
#CMD su - fuse /home/fuse/fuse-fabric/bin/start
#CMD su - fuse /home/fuse/fuse-fabric/bin/karaf

CMD /home/fuse/fuse-fabric/bin/karaf
